class RateLimiterConfigurationError(Exception): ...


class UnconfiguredRateLimiterError(RateLimiterConfigurationError): ...


class UnsupportedRateLimiterPolicyError(RateLimiterConfigurationError): ...


class RateLimitError(Exception): ...


class TokenConsumptionOverLimitError(RateLimitError): ...
