class CookieError(Exception): ...


class HeaderError(Exception): ...


class InvalidForwardedHeaderError(HeaderError): ...


class ConflictingForwardedHeadersError(HeaderError): ...


class SuspiciousOperationError(Exception): ...


class ClientDisconnectedError(Exception): ...


class MalformedJSONError(Exception): ...


class UnsupportedContentTypeError(Exception): ...


class MalformedMultipartError(Exception): ...
