class CookieError(Exception): ...


class HeaderError(Exception): ...


class InvalidForwardedHeaderError(HeaderError): ...


class ConflictingForwardedHeadersError(HeaderError): ...


class SuspiciousOperationError(Exception): ...
