"""
Create jobs table

Revision ID: 3969e5e13f3f
Revises:
Create Date: 2025-08-14 12:05:48.993219
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = "3969e5e13f3f"
down_revision: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.INTEGER(), "sqlite"),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("queue", sa.String(255), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "attempts",
            sa.SmallInteger()
            .with_variant(mysql.SMALLINT(unsigned=True), "mysql")
            .with_variant(sa.INTEGER(), "sqlite"),
            nullable=False,
        ),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_queue", "jobs", ["queue"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_queue", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
