name: Linting

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHONUTF8: 1

jobs:
  tests:
    name: Type checking
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14

      - name: Install dependencies
        run: uv sync --group lint --group test

      - name: Run typechecking
        run: uv run mypy
