name: Linting

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHONUTF8: 1

jobs:
  tests:
    name: Type checking
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.14

      - name: Install dependencies
        run: uv sync --group lint --group test

      - name: Run typechecking
        run: uv run mypy
