name: Linting

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHONUTF8: 1

jobs:
  tests:
    name: Type checking
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: uv sync --group lint

      - name: Run typechecking
        run: uv run mypy
