name: Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: poetry

      - name: Build package
        run: poetry build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    name: Release
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/project/expanse/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Check Version
        id: check-version
        run: |
          [[ "${GITHUB_REF#refs/tags/}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo prerelease=true >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
